### ISSUE TITLE
Obuspa is sending an unexpected ERROR message without code or message

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#59]
Hi,

The issue I want to report is that obuspa is sending an unexpected ERROR message without id, code or message.

To reproduce it, send an OPERATE message to the agent with the followings parameters:

```
{
    "command": "Device.Reboot()",
    "commandKey": "reboot",
    "sendResp": true,
    "inputArgs": {}
}
```

Then the following sequence will happen:

1) The agent sends an OPERATE_RESP
2) The agent reboots
3) The agent sends an ERROR message with null id and this parameters:

```
{
    "errorCode": 0,
    "errorMsg": "",
    "paramErrs": []
}
```

4) The agent sends a NOTIFY message with Boot! event

I think that the step 3) maybe is a bug, or maybe someone can explain me that behaviour.

I'm using version 6.0 of obuspa (before I was using 1.0 and I didn't have this issue).

Thanks in advance!

**Comment by holme-r** [comment]
I'm unable to reproduce this and cannot see an obvious reason for ERROR being sent after the reboot (it shouldn't be). Can you provide a callstack for when ERROR_RESP_Create() gets called after the reboot. You might be able to get this by adding a call to USP_LOG_Callstack() in ERROR_RESP_Create(). Alternatively use gdb.

**Comment by italktothewind** [comment]
I'm trying not to recompile or debug the obuspa code because I'm using it just as a test agent for a controller.

Maybe I can show you the logs.

I have the following docker compose file:

```
version: '3.3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
    volumes:
      - ./volumes/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  agent:
    image: obuspa:latest
    command: bash -c "obuspa -r /obuspa/factory_reset.txt -p -v4"
    volumes:
      - ./volumes/obuspa/factory_reset.txt:/obuspa/factory_reset.txt
    depends_on:
      - mosquitto
    restart: always
```

I attached the logs of the docker compose. 

There you can see that ERROR message is not being logged (but is definitely being sent because I receive it each time I reproduce the issue), only the OPERATE_RESP and the NOTIFY messages are logged.

Any advice? Thanks!

[docker_logs.txt](https://github.com/BroadbandForum/obuspa/files/9419337/docker_logs.txt)
